export const deals = [
  {
    id: 1,
    name: "FinTech Innovator",
    sector: "Fintech",
    stage: "Series A",
    range: "₹50L - ₹2Cr",
    color: "bg-purple-100",
    icon: "document",
    status: "Open",
    slug: "fintech-innovator",
    imageUrl: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=400&q=80",
    description: "AI-powered financial analytics platform revolutionizing investment decision-making for institutional investors across emerging markets.",
    irr: "25-30%",
  },
  // {
  //   id: 2,
  //   name: "Manufacturing Giant",
  //   sector: "Manufacturing",
  //   stage: "Growth",
  //   range: "₹1Cr - ₹5Cr",
  //   color: "bg-purple-100",
  //   icon: "heart",
  //   status: "Open",
  //   slug: "manufacturing-giant",
  //   imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80"
  // },
  {
    id: 3,
    name: "E-Commerce Plus",
    sector: "Retail",
    stage: "Series A",
    range: "₹7.5Cr - ₹22.5Cr",
    color: "bg-purple-100",
    icon: "cart",
    status: "Open",
    slug: "ecommerce-plus",
    imageUrl: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80",
    description: "Next-gen e-commerce platform enabling seamless online retail experiences for millions of users.",
    irr: "18-22%",
  },
  {
    id: 4,
    name: "HealthTech Pioneer",
    sector: "Healthcare",
    stage: "Pre-IPO",
    range: "₹25L - ₹1Cr",
    color: "bg-purple-100",
    icon: "heart",
    status: "Closed",
    slug: "healthtech-pioneer",
    imageUrl: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80",
    description: "Digital health platform connecting patients with healthcare providers through innovative telemedicine solutions.",
    irr: "30-35%",
  },
  {
    id: 5,
    name: "GreenEnergy Solutions",
    sector: "Clean Energy",
    stage: "Seed",
    range: "₹2.25Cr - ₹5.25Cr",
    color: "bg-purple-100",
    icon: "bolt",
    status: "Open",
    slug: "greenenergy-solutions",
    imageUrl: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=400&q=80",
    description: "Leading renewable energy solutions provider with operations across 15 countries and growing market presence.",
    irr: "20-25%",
  },
  {
    id: 6,
    name: "EduTech Innovator",
    sector: "EdTech",
    stage: "Series A",
    range: "₹6Cr - ₹11.25Cr",
    color: "bg-purple-100",
    icon: "book",
    status: "Closed",
    slug: "edutech-innovator",
    imageUrl: "https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=400&q=80",
    description: "Revolutionary educational technology platform making quality education accessible through AI-driven personalized learning.",
    irr: "35-40%",
  },
  {
    id: 8,
    name: "CyberSafe Solutions",
    sector: "Cybersecurity",
    stage: "Series B",
    range: "₹15Cr - ₹30Cr",
    color: "bg-purple-100",
    icon: "shield",
    status: "Open",
    slug: "cybersafe-solutions",
    imageUrl: "https://images.unsplash.com/photo-1510511459019-5dda7724fd87?auto=format&fit=crop&w=400&q=80",
    description: "Advanced cybersecurity solutions provider protecting enterprises from emerging digital threats with AI-powered defense systems.",
    irr: "28-32%",
  },
  {
    id: 9,
    name: "WomenLead Ventures",
    sector: "Diversity",
    stage: "Seed",
    range: "₹1.5Cr - ₹4.5Cr",
    color: "bg-purple-100",
    icon: "user-group",
    status: "Open",
    slug: "womenlead-ventures",
    imageUrl: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=400&q=80",
    description: "Empowering women entrepreneurs through funding and mentorship in diverse sectors.",
    irr: "22-27%",
  },
  {
    id: 10,
    name: "BlockChain Innovation",
    sector: "Blockchain",
    stage: "Series A",
    range: "₹7.5Cr - ₹18.75Cr",
    color: "bg-purple-100",
    icon: "cube",
    status: "Open",
    slug: "blockchain-innovation",
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80",
    description: "Blockchain-based platform enabling secure and transparent digital transactions for global businesses.",
    irr: "19-24%",
  },
  {
    id: 12,
    name: "SaaS Platform",
    sector: "SaaS",
    stage: "Series B",
    range: "₹22.5Cr - ₹45Cr",
    color: "bg-purple-100",
    icon: "cloud",
    status: "Open",
    slug: "saas-platform",
    imageUrl: "https://images.unsplash.com/photo-1461344577544-4e5dc9487184?auto=format&fit=crop&w=400&q=80",
    description: "Cloud-based SaaS platform streamlining business operations for SMEs worldwide.",
    irr: "21-26%",
  },
  {
    id: 13,
    name: "D2C Brands Network",
    sector: "Retail",
    stage: "Series A",
    range: "₹9Cr - ₹16.5Cr",
    color: "bg-purple-100",
    icon: "shopping-bag",
    status: "Open",
    slug: "d2c-brands-network",
    imageUrl: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80",
    description: "Network of direct-to-consumer brands leveraging digital channels for rapid growth.",
    irr: "23-29%",
  },
];