import "./globals.css";

export const metadata = {
  title: "Equigini | Digital Investment Banker",
  description: "Generated by create next app",
  // icons: {
  //   icon: '/favicon.png',
  //   shortcut: '/favicon.png',
  //   apple: '/favicon.png',
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
      <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      <link rel="shortcut icon" href="/favicon.ico" />
      <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
      <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
